packages:
  - "packages/*"
  - "OPS/CLI"

allowBuilds:
  '@google/genai': set this to true or false
  bcrypt: set this to true or false
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  unrs-resolver: set this to true or false

overrides:
  "@radix-ui/react-compose-refs": "1.0.0"
