  class SlidePresentation {
    constructor(){this.slides=[...document.querySelectorAll('.slide')];this.bar=document.querySelector('.progress i');this.hint=document.querySelector('.hint');this.stage=document.getElementById('deckStage');this.currentSlide=0;this.touchX=0;this.setPageNumbers();this.setupStageScale();this.setupKeyboardNav();this.setupTouchNav();this.setupWheelNav();this.showSlide(0)}
    setPageNumbers(){this.slides.forEach((s,i)=>{const p=s.querySelector('.page');if(p)p.textContent=String(i+1).padStart(2,'0')})}
    setupStageScale(){const scale=()=>{const factor=Math.min(innerWidth/1920,innerHeight/1080);const x=(innerWidth-1920*factor)/2;const y=(innerHeight-1080*factor)/2;this.stage.style.transform=`translate(${x}px,${y}px) scale(${factor})`};scale();addEventListener('resize',scale)}
    setupKeyboardNav(){addEventListener('keydown',e=>{if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();this.showSlide(this.currentSlide+1)}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();this.showSlide(this.currentSlide-1)}else if(e.key.toLowerCase()==='f')this.toggleFullscreen()})}
    setupTouchNav(){addEventListener('touchstart',e=>{this.touchX=e.changedTouches[0].screenX},{passive:true});addEventListener('touchend',e=>{const dx=e.changedTouches[0].screenX-this.touchX;if(Math.abs(dx)>50)this.showSlide(this.currentSlide+(dx<0?1:-1))},{passive:true})}
    setupWheelNav(){let lock=false;addEventListener('wheel',e=>{if(lock)return;lock=true;this.showSlide(this.currentSlide+(e.deltaY>0?1:-1));setTimeout(()=>lock=false,450)},{passive:true})}
    showSlide(index){this.currentSlide=Math.max(0,Math.min(index,this.slides.length-1));this.slides.forEach((s,i)=>{s.classList.toggle('active',i===this.currentSlide);s.classList.toggle('visible',i===this.currentSlide)});this.bar.style.width=((this.currentSlide+1)/this.slides.length*100)+'%';this.hint.textContent=`${this.currentSlide+1} / ${this.slides.length} · ← → 翻页 · F 全屏`}
    toggleFullscreen(){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()}
  }
  const presentation=new SlidePresentation();document.querySelector('.fullscreen').onclick=()=>presentation.toggleFullscreen();addEventListener('click',e=>{if(e.target.closest('.controls'))return;presentation.showSlide(presentation.currentSlide+(e.clientX>innerWidth/2?1:-1))});
